namespace PromoStandards.REST.Core.ProductPricingConfiguration.ServiceReference;

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.promostandards.org/WSDL/PricingAndConfiguration/1.0.0/", ConfigurationName="PricingAndConfigurationService")]
public interface PricingAndConfigurationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="getAvailableLocations", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AvailableLocation[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Color[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DecorationMethod[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CurrencySupported[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Product[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FobPoint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AvailableCharge[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PartPrice[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Part[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ChargePrice[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Charge[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Decoration[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Location[]))]
    System.Threading.Tasks.Task<getAvailableLocationsResponse1> getAvailableLocationsAsync(getAvailableLocationsRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="getDecorationColors", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AvailableLocation[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Color[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DecorationMethod[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CurrencySupported[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Product[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FobPoint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AvailableCharge[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PartPrice[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Part[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ChargePrice[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Charge[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Decoration[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Location[]))]
    System.Threading.Tasks.Task<getDecorationColorsResponse1> getDecorationColorsAsync(getDecorationColorsRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="getFobPoints", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AvailableLocation[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Color[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DecorationMethod[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CurrencySupported[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Product[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FobPoint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AvailableCharge[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PartPrice[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Part[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ChargePrice[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Charge[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Decoration[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Location[]))]
    System.Threading.Tasks.Task<getFobPointsResponse1> getFobPointsAsync(getFobPointsRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="getAvailableCharges", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AvailableLocation[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Color[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DecorationMethod[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CurrencySupported[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Product[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FobPoint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AvailableCharge[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PartPrice[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Part[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ChargePrice[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Charge[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Decoration[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Location[]))]
    System.Threading.Tasks.Task<getAvailableChargesResponse1> getAvailableChargesAsync(getAvailableChargesRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="getConfigurationAndPricing", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AvailableLocation[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Color[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DecorationMethod[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CurrencySupported[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Product[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FobPoint[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AvailableCharge[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PartPrice[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Part[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ChargePrice[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Charge[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Decoration[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Location[]))]
    System.Threading.Tasks.Task<getConfigurationAndPricingResponse1> getConfigurationAndPricingAsync(getConfigurationAndPricingRequest1 request);
}